components:
  schemas:
    ChatMessageRequest:
      properties:
        message:
          title: Message
          type: string
      required:
      - message
      title: ChatMessageRequest
      type: object
    ChatMessageResponse:
      properties:
        items:
          items:
            $ref: '#/components/schemas/Item'
          title: Items
          type: array
        message:
          title: Message
          type: string
      required:
      - message
      - items
      title: ChatMessageResponse
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    Item:
      properties:
        description:
          title: Description
          type: string
        id:
          title: Id
          type: string
        image_url:
          title: Image Url
          type: string
      required:
      - id
      - description
      - image_url
      title: Item
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
      - loc
      - msg
      - type
      title: ValidationError
      type: object
info:
  description: "ChatGPT\u3092\u30A4\u30F3\u30BF\u30D5\u30A7\u30FC\u30B9\u306B\u3057\
    \u305F\u3001\u5BFE\u8A71\u578B\u306E\u5546\u54C1\u691C\u7D22\u30C7\u30E2\u30C4\
    \u30FC\u30EB\u306EAPI\u3067\u3059\u3002"
  title: "\u3086\u308B\u3075\u308F\u5546\u54C1\u691C\u7D22Demo API"
  version: 1.0.0
openapi: 3.0.2
paths:
  /chat-messages/{session_id}:
    post:
      operationId: post_chat_message_chat_messages__session_id__post
      parameters:
      - in: path
        name: session_id
        required: true
        schema:
          title: Session Id
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessageResponse'
          description: Successful Response
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
          description: Validation Error
      summary: Post Chat Message
